//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHocKiDTO
    {
        public int Id { get; set; }
        public string PhongHoc { get; set; }
        public System.DateTime NgayHoc { get; set; }
        public string GioHoc { get; set; }
        public int TenHocKi { get; set; }
        public int TenMonHoc { get; set; }
        public int TenGiangVien { get; set; }
    }
}
