//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public GiangVien()
        {
            this.CTHocKis = new HashSet<CTHocKi>();
        }
    
        public int Id { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> IdMonHoc { get; set; }
        public int IdTaiKhoan { get; set; }
    
        public virtual ICollection<CTHocKi> CTHocKis { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
