//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public Lop()
        {
            this.HocSinhs = new HashSet<HocSinh>();
        }
    
        public int Id { get; set; }
        public string TenLop { get; set; }
    
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
    }
}
