//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public HocSinh()
        {
            this.TKBs = new HashSet<TKB>();
            this.TongKetHKs = new HashSet<TongKetHK>();
        }
    
        public int Id { get; set; }
        public string MSSV { get; set; }
        public string HoTen { get; set; }
        public DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
    
        public virtual Lop Lop { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<TKB> TKBs { get; set; }
        public virtual ICollection<TongKetHK> TongKetHKs { get; set; }
    }
}
