//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongKetHK
    {
        public int Id { get; set; }
        public Nullable<int> DiemTB { get; set; }
        public int HocKiID { get; set; }
        public int HocSinhID { get; set; }
    
        public virtual HocKi HocKi { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
