//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Topic3.DataLayer
{
    using Project_Topic3.DataLayer.DAO;
    using System;
    using System.Collections.Generic;
    
    public partial class TongKetHK
    {
        public int Id { get; set; }
        public Nullable<int> DiemTB { get; set; }
        public int HocKiID { get; set; }
        public int HocSinhID { get; set; }

        public virtual HocKi HocKi { get {
            HocKiDAO hocKiDAO = new HocKiDAO();
            return hocKiDAO.get(HocKiID);
        }
            set { }
        }
        public virtual HocSinh HocSinh { get {
            HocSinhDAO hocSinhDAO = new HocSinhDAO();
            return hocSinhDAO.get(HocSinhID);
        }
            set { }
        }
    }
}
